---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: iss-tracker
        container_name: iss-tracker
        ports:
            - "3000:3000"